<?php
/**
 * @file
 * SmugMug module file.
 */

function smugmug_block_info() {

  $blocks['smugmug_gallery_block'] = array(
    'info' => t('SmugMug Photo Gallery'),
    'cache'=> DRUPAL_CACHE_PER_PAGE,
  );



  return $blocks;
}//end of SmugMug block info

/**
 * Create a drupal content type with the following fields:
 * - Thumbnail image_src
 * - Updated Date for sorting the image_src
 * - SmugMug Album Id
 * - SmugMug Album Key

 * So this module reads the Album Id and Album Key from your node and bring the Gallery data from SmugMug API

 */

function smugmug_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'smugmug_gallery_block':
      $title="";
      $layout ="";
      $query = new EntityFieldQuery();
      $query->fieldOrderBy('field_updated_date', 'value', 'DESC');
      $result = $query->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', 'page')
        ->propertyCondition('status', NODE_PUBLISHED)
        ->pager(12)
        ->execute();
      $nodes = node_load_multiple(array_keys($result['node']));
      $pager= theme('pager');
      $all_gallery_output="<div class='row'>";
      $row_breaker=0;
      foreach ($nodes as $record) {
        $gallery_link="";
        $title= $record->title;
        $image_src = file_create_url($record->field_smugmug_thumbnail['und'][0]['uri']);
        $album_id=$record->field_gallery_url['und'][0]['value'];
        $album_key=$record->field_gallery_value['und'][0]['value'];
        $updated_date=date('j F Y',strtotime(($record->field_updated_date['und'][0]['value'])));
        $gallery_link=$gallery_link.'<div class="col-md-4 col-sm-6 col-xs-12 margin40-top-bottom news-thumbnail"><span class="img-responsive margin20-bottom" ><div class="mbr-gallery-item mbr-gallery-item__mobirise3 mbr-gallery-item--p0" data-tags="Awesome" data-video-url="false"><div href="#lb-gallery1-'.$album_id.'" data-slide-to="0" data-toggle="modal"><img src="'.$image_src.'" style="width: 360px;  height: 270px;" /> <span class="icon-focus"></span></div></div>       </span><div class="grey" >'.$updated_date.'</div><h3 style="color: #545454;">'.$title.'</h3></div>';
        $get_render_output = smugmug_content_builder($album_id,$album_key);
        $gallery_link=$gallery_link.$get_render_output;
        $all_gallery_output=$all_gallery_output.$gallery_link;
        if(($row_breaker+1)%3==0)
          $all_gallery_output=$all_gallery_output."</div><div class='row'>";
        $row_breaker = $row_breaker+1;
      }
      $all_gallery_output=$all_gallery_output."</div>";
      $block['subject'] = t('SmugMug Gallery');
      $block['content'] =$all_gallery_output.$pager;
      break;
  }
  return $block;
}//end of reliefweb view block method

/**
 * Fetch API data from SmugMug.
 *
 *
 */

function smugmug_content_builder($album_id,$album_key){
  // Add your SmugMug API Key
  $api_key = '';

  //add your SmugMug API Secrete
  $api_secrete = '';

  
  $context = stream_context_create(array(
   'http' => array(
       'header'  => "Authorization: Basic " . base64_encode("$api_key:$api_secrete")
     )
  ));
  $get_image ='http://api.smugmug.com/services/api/json/1.3.0/?method=smugmug.images.get&APIKey='.$api_key.'&AlbumKey='.$album_key.'&AlbumID='.$album_id;
  $data_get_image = json_decode(file_get_contents("$get_image", false, $context));
  $album="";
  $counter_item = 0;
  foreach ($data_get_image->Album->Images as $item) {
    $image_key = $item->Key;
    $get_image_url ='http://api.smugmug.com/services/api/json/1.3.0/?method=smugmug.images.getInfo&APIKey='.$api_key.'&ImageKey='.$image_key;
    $data_get_image_url = json_decode(file_get_contents("{$get_image_url}", false, $context));
    $url = $data_get_image_url->Image->LargeURL;
    $caption = $data_get_image_url->Image->Caption;
    if ($counter_item==0){
      $album=$album. '<div class="carousel-item active"><img src="'.$url.'" ><div style="background: rgba(0,0,0,0.8); opacity: 1; color: #fff;padding: 10px;font-size:12px;">'.$caption.'</div></div>';
    }
    else{
      $album=$album. '<div class="carousel-item"><img src="'.$url.'" ><div style="background: rgba(0,0,0,0.8); opacity: 1; color:#fff; padding: 10px;font-size:12px;">'.$caption.'</div></div>';
    }
    $counter_item =$counter_item+1;
 }
  return $render_output='
    <div data-app-prevent-settings="" class="mbr-slider modal fade carousel slide" tabindex="-1" data-keyboard="true" data-interval="false" id="lb-gallery1-'.$album_id.'" >
    <div class="modal-dialog" style="top: 0%; width: 850px;">
    <div class="modal-content"><div class="modal-body">'.$indicator.'<div class="carousel-inner">'.$album.'</div><a class="left carousel-control" role="button" data-slide="prev" href="#lb-gallery1-'.$album_id.'">
    <span class="icon-prev" aria-hidden="true"></span><span class="sr-only">Previous</span></a><a class="right carousel-control" role="button" data-slide="next" href="#lb-gallery1-'.$album_id.'">
    <span class="icon-next" aria-hidden="true"></span><span class="sr-only">Next</span></a></div></div></div></div>';
  echo $gallery_link.$render_output;
}
